name: pokedex_bloc
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0

  #check if has internet
  internet_connection_checker: 

  # display top overlay
  overlay_support:

  # check if has wifi, mobile, no network
  connectivity_plus: ^2.2.0
  http: ^0.13.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
